/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const allCoreContracts = {
  type: "category",
  label: "DAO",
  collapsed: false,
  items: ["core/dao-factory", "core/dao-registry"],
};

const allExtensions = {
  type: "category",
  label: "Extensions",
  collapsed: true,
  items: [
    "extensions/bank-extension",
    "extensions/erc20-extension",
    "extensions/nft-extension",
    "extensions/executor-extension",
  ],
};

const allAdapters = {
  type: "category",
  label: "Adapters",
  collapsed: false,
  items: [
    {
      Configuration: [
        "adapters/configuration/configuration-adapter",
        "adapters/configuration/managing-adapter",
      ],
    },
    {
      Distribution: [
        "adapters/distribution/distribute-adapter",
        "adapters/distribution/withdraw-adapter",
      ],
    },
    {
      Funding: ["adapters/funding/financing-adapter"],
    },
    {
      Kick: [
        "adapters/exiting/guild-kick-adapter",
        "adapters/exiting/rage-quit-adapter",
      ],
    },
    {
      Onboarding: [
        "adapters/onboarding/coupon-onboarding-adapter",
        "adapters/onboarding/onboarding-adapter",
        "adapters/onboarding/tribute-adapter",
        "adapters/onboarding/tribute-nft-adapter",
      ],
    },
    {
      Voting: [
        "adapters/voting/basic-voting-adapter",
        "adapters/voting/batch-voting-adapter",
        "adapters/voting/offchain-voting-adapter",
      ],
    },
  ],
};

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: [
        "intro/overview-and-benefits",
        {
          type: "category",
          label: "Comparison",
          collapsed: true,
          items: ["intro/comparison/moloch-v1", "intro/comparison/moloch-v2"],
        },
        {
          type: "category",
          label: "Design Principles",
          collapsed: true,
          items: [
            "intro/design/architecture",
            "intro/design/core",
            "intro/design/extensions",
            "intro/design/adapters",
            "intro/design/access-control",
          ],
        },
        {
          type: "category",
          label: "Smart Contracts",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Core Contracts",
              collapsed: true,
              items: ["core/introduction", allCoreContracts],
            },
            {
              type: "category",
              label: "Extension Contracts",
              collapsed: true,
              items: ["extensions/introduction", allExtensions],
            },
            {
              type: "category",
              label: "Adapters Contracts",
              collapsed: true,
              items: ["adapters/introduction", allAdapters],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "NFT DAO",
          collapsed: true,
          items: [
            "tutorial/nft-dao/installation",
            "tutorial/nft-dao/configuration",
            "tutorial/nft-dao/deployment",
            "tutorial/nft-dao/interacting",
          ],
        },
      ],
    },
  ],

  core: ["core/introduction", allCoreContracts],
  extensions: ["extensions/introduction", allExtensions],
  adapters: ["adapters/introduction", allAdapters],
};
